/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jadwalpenerbanganpesawat;

/**
 *
 * @author Iqbal Albana
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        airlines1 = new javax.swing.JLabel();
        flight1 = new javax.swing.JLabel();
        tujuan1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        airlines2 = new javax.swing.JLabel();
        flight2 = new javax.swing.JLabel();
        tujuan2 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        airlines3 = new javax.swing.JLabel();
        flight3 = new javax.swing.JLabel();
        tujuan3 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        airlines4 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        flight4 = new javax.swing.JLabel();
        tujuan4 = new javax.swing.JLabel();
        airlines5 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        flight5 = new javax.swing.JLabel();
        tujuan5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIST KERETA API DARI STASIUN KOTA BARU MALANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 490, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Jadwal Penerbangan Bandara Sukarno Hatta --", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(20, 50, 430, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AIRLINES");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 0, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TUJUAN");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(350, 0, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FLIGHT");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(180, 0, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TIME");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(520, 0, 110, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 90, 650, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        airlines1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(airlines1);
        airlines1.setBounds(40, 30, 140, 30);

        flight1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(flight1);
        flight1.setBounds(220, 30, 140, 30);

        tujuan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(tujuan1);
        tujuan1.setBounds(400, 30, 140, 30);

        time1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(time1);
        time1.setBounds(570, 30, 110, 30);

        airlines2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(airlines2);
        airlines2.setBounds(40, 60, 140, 30);

        flight2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(flight2);
        flight2.setBounds(220, 60, 140, 30);

        tujuan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(tujuan2);
        tujuan2.setBounds(400, 60, 140, 30);

        time2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(time2);
        time2.setBounds(570, 60, 110, 30);

        airlines3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(airlines3);
        airlines3.setBounds(40, 90, 140, 30);

        flight3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(flight3);
        flight3.setBounds(220, 90, 140, 30);

        tujuan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(tujuan3);
        tujuan3.setBounds(400, 90, 140, 30);

        time3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(time3);
        time3.setBounds(570, 90, 110, 30);

        airlines4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(airlines4);
        airlines4.setBounds(40, 120, 140, 30);

        time4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(time4);
        time4.setBounds(570, 120, 110, 30);

        flight4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(flight4);
        flight4.setBounds(220, 120, 140, 30);

        tujuan4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(tujuan4);
        tujuan4.setBounds(400, 120, 140, 30);

        airlines5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(airlines5);
        airlines5.setBounds(40, 150, 140, 30);

        time5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(time5);
        time5.setBounds(570, 150, 110, 30);

        flight5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(flight5);
        flight5.setBounds(220, 150, 140, 30);

        tujuan5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(tujuan5);
        tujuan5.setBounds(400, 150, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 90, 670, 200);

        setBounds(0, 0, 728, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedItem().equals("-- Jadwal Penerbangan Bandara Sukarno Hatta --")){
            airlines1.setText("");
            flight1.setText("");
            tujuan1.setText("");
            time1.setText("");

            airlines2.setText("");
            flight2.setText("");
            tujuan2.setText("");
            time2.setText("");

            airlines3.setText("");
            flight3.setText("");
            tujuan3.setText("");
            time3.setText("");

            airlines4.setText("");
            flight4.setText("");
            tujuan4.setText("");
            time4.setText("");

            airlines5.setText("");
            flight5.setText("");
            tujuan5.setText("");
            time5.setText("");
        }else
        if(jComboBox1.getSelectedItem().equals("Senin")){
            airlines1.setText("Lion Air");
            flight1.setText("JT 0515");
            tujuan1.setText("NGEBRUK");
            time1.setText("18:40");

            airlines2.setText("Garuda Indonesia");
            flight2.setText("GA 0247");
            tujuan2.setText("PUJON");
            time2.setText("19:25");

            airlines3.setText("Lion Air");
            flight3.setText("JT 0509");
            tujuan3.setText("TUBAN");
            time3.setText("20:10");

            airlines4.setText("");
            flight4.setText("");
            tujuan4.setText("");
            time4.setText("");

            airlines5.setText("");
            flight5.setText("");
            tujuan5.setText("");
            time5.setText("");
        }else
        if(jComboBox1.getSelectedItem().equals("Selasa")){
            airlines1.setText("Wings Air");
            flight1.setText("IW 1802");
            tujuan1.setText("DENPASAR");
            time1.setText("06:00");

            airlines2.setText("Sriwijaya Air");
            flight2.setText("SJ 0221");
            tujuan2.setText("SURABAYA");
            time2.setText("06:10");

            airlines3.setText("Lion Air");
            flight3.setText("JT 0511");
            tujuan3.setText("SAWOJAJAR");
            time3.setText("07:25");

            airlines4.setText("Lion Air");
            flight4.setText("JT 0624");
            tujuan4.setText("PROBOLINGGO");
            time4.setText("08:00");

            airlines5.setText("");
            flight5.setText("");
            tujuan5.setText("");
            time5.setText("");
        }else
        if (jComboBox1.getSelectedItem().equals("Rabu")){
            airlines1.setText("Sriwijaya Air");
            flight1.setText("SJ 0221");
            tujuan1.setText("NGAWI");
            time1.setText("09:10");

            airlines2.setText("Lion Air");
            flight2.setText("JT 0511");
            tujuan2.setText("SRENGAT");
            time2.setText("07:25");

            airlines3.setText("Lion Air");
            flight3.setText("JT 0624");
            tujuan3.setText("NGANJUK");
            time3.setText("08:00");
            
            airlines4.setText("");
            flight4.setText("");
            tujuan4.setText("");
            time4.setText("");

            airlines5.setText("");
            flight5.setText("");
            tujuan5.setText("");
            time5.setText("");
        }else
        if (jComboBox1.getSelectedItem().equals("Kamis")){
            airlines1.setText("Wings Air");
            flight1.setText("JT 0515");
            tujuan1.setText("NGEBRUK");
            time1.setText("19:40");

            airlines2.setText("Garuda Indonesia");
            flight2.setText("GA 0247");
            tujuan2.setText("PUJON");
            time2.setText("19:00");

            airlines3.setText("Sriwijaya Air");
            flight3.setText("JT 0509");
            tujuan3.setText("TUBAN");
            time3.setText("20:10");
            
            airlines4.setText("");
            flight4.setText("");
            tujuan4.setText("");
            time4.setText("");

            airlines5.setText("");
            flight5.setText("");
            tujuan5.setText("");
            time5.setText("");
        }else
        if (jComboBox1.getSelectedItem().equals("Jumat")){
            airlines1.setText("Wings Air");
            flight1.setText("JT 0515");
            tujuan1.setText("NGEBRUK");
            time1.setText("19:40");

            airlines2.setText("Garuda Indonesia");
            flight2.setText("GA 0247");
            tujuan2.setText("PUJON");
            time2.setText("19:00");
            
            airlines3.setText("");
            flight3.setText("");
            tujuan3.setText("");
            time3.setText("");

            airlines4.setText("");
            flight4.setText("");
            tujuan4.setText("");
            time4.setText("");

            airlines5.setText("");
            flight5.setText("");
            tujuan5.setText("");
            time5.setText("");
        }
        else
        if (jComboBox1.getSelectedItem().equals("Sabtu")){
            airlines1.setText("Wings Air");
            flight1.setText("IW 1802");
            tujuan1.setText("DENPASAR");
            time1.setText("06:00");

            airlines2.setText("Sriwijaya Air");
            flight2.setText("SJ 0221");
            tujuan2.setText("SURABAYA");
            time2.setText("06:10");

            airlines3.setText("Lion Air");
            flight3.setText("JT 0511");
            tujuan3.setText("SAWOJAJAR");
            time3.setText("07:25");

            airlines4.setText("Lion Air");
            flight4.setText("JT 0624");
            tujuan4.setText("PROBOLINGGO");
            time4.setText("08:00");

            airlines5.setText("Garuda Indonesia");
            flight5.setText("GA 0891");
            tujuan5.setText("MALANG");
            time5.setText("05:10");
        }else
        if (jComboBox1.getSelectedItem().equals("Minggu")){
            airlines1.setText("Wings Air");
            flight1.setText("JT 0515");
            tujuan1.setText("NGEBRUK");
            time1.setText("19:40");

            airlines2.setText("Garuda Indonesia");
            flight2.setText("GA 0247");
            tujuan2.setText("PUJON");
            time2.setText("19:00");
            
            airlines3.setText("Lion Air");
            flight3.setText("JT 0692");
            tujuan3.setText("BANYUWANGI");
            time3.setText("09:45");

            airlines4.setText("Wings Air");
            flight4.setText("JT 0568");
            tujuan4.setText("Jember");
            time4.setText("10:00");

            airlines5.setText("");
            flight5.setText("");
            tujuan5.setText("");
            time5.setText("");
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlines1;
    private javax.swing.JLabel airlines2;
    private javax.swing.JLabel airlines3;
    private javax.swing.JLabel airlines4;
    private javax.swing.JLabel airlines5;
    private javax.swing.JLabel flight1;
    private javax.swing.JLabel flight2;
    private javax.swing.JLabel flight3;
    private javax.swing.JLabel flight4;
    private javax.swing.JLabel flight5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    private javax.swing.JLabel tujuan1;
    private javax.swing.JLabel tujuan2;
    private javax.swing.JLabel tujuan3;
    private javax.swing.JLabel tujuan4;
    private javax.swing.JLabel tujuan5;
    // End of variables declaration//GEN-END:variables
}
